version: "3.3"

services:
  ocsgw:
    container_name: ocsgw
    build: ocsgw
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/config/pantel-prod.json
      - GRPC_SERVER=ocs.endpoints.pantel-2decb.cloud.goog
      - GRPC_ENCRYPTION=true

  auth-server:
    container_name: auth-server
    build: auth-server
    ports:
      - "8080:8080"
