# This docker-compose is used for load testing Diameter traffic using Seagull.

version: "3.7"

services:
  prime:
    container_name: prime
    build:
      context: prime
      dockerfile: Dockerfile.test
    environment:
      - GCP_PROJECT_ID=${GCP_PROJECT_ID}
      # used by Stackdriver Tracing
      - GOOGLE_CLOUD_PROJECT=${GCP_PROJECT_ID}
      # used by Datastore, Pub/Sub, Stackdriver Tracing
      - GOOGLE_APPLICATION_CREDENTIALS=/secret/prime-service-account.json
      - PUBSUB_EMULATOR_HOST=pubsub-emulator:8085
      - PUBSUB_PROJECT_ID=${GCP_PROJECT_ID}
      - JUMIO_API_TOKEN=
      - JUMIO_API_SECRET=
      - STRIPE_API_KEY=${STRIPE_API_KEY}
      - STRIPE_ENDPOINT_SECRET=${STRIPE_ENDPOINT_SECRET}
      - DATASTORE_EMULATOR_HOST=localhost:9090
      - DATASTORE_PROJECT_ID=${GCP_PROJECT_ID}
      - MANDRILL_API_KEY=
      - ACCEPTANCE_TESTING=true
    ports:
      - "9090:8080"
      - "8082:8082"
    depends_on:
      - "datastore-emulator"
      - "pubsub-emulator"
      - "neo4j"
    command: ["/bin/bash", "./wait.sh"]
    tmpfs:
      - /data
    networks:
      net:
        aliases:
          - "prime"
        ipv4_address: 172.16.238.5
      default:

  ocsgw:
    container_name: ocsgw
    build: ocsgw
    depends_on:
      - "pubsub-emulator"
      - "prime"
    command: ["./wait.sh"]
    environment:
      - DISABLE_TLS=true
      - OCS_GRPC_SERVER=prime:8082
      - METRICS_GRPC_SERVER=prime:8083
      - SERVICE_FILE=prime-service-account.json
      - GOOGLE_CLOUD_PROJECT=${GCP_PROJECT_ID}
      - PUBSUB_EMULATOR_HOST=pubsub-emulator:8085
      - PUBSUB_PROJECT_ID=${GCP_PROJECT_ID}
      - PUBSUB_CCR_TOPIC_ID=ocs-ccr
      - PUBSUB_CCA_TOPIC_ID=ocs-cca
      - PUBSUB_CCA_SUBSCRIPTION_ID=ocsgw-cca-sub
      - PUBSUB_ACTIVATE_SUBSCRIPTION_ID=ocsgw-activate-sub
      - DIAMETER_CONFIG_FILE=server-jdiameter-config.xml
      - OCS_DATASOURCE_TYPE=Local
      - CONFIG_FOLDER=/config/
      - "JAVA_OPTS=-Xms512m -Xmx1024m -server"
    volumes:
      - ./ocsgw/cert:/cert/
      - ./ocsgw/config:/config/
    networks:
      net:
        aliases:
          - "ocsgw"
        ipv4_address: 172.16.238.3
      default:

  neo4j:
    container_name: "neo4j"
    image: neo4j:3.4.9
    environment:
      - NEO4J_AUTH=none
    ports:
      - "7687:7687"
      - "7474:7474"
    tmpfs: "/data"

  pubsub-emulator:
    container_name: pubsub-emulator
    image: knarz/pubsub-emulator

  datastore-emulator:
    container_name: datastore-emulator
    image: google/cloud-sdk:218.0.0
    expose:
      - "8081"
    environment:
      - CLOUDSDK_CORE_PROJECT=${GCP_PROJECT_ID}
      - DATASTORE_DATASET=${GCP_PROJECT_ID}
    command: ["gcloud", "beta", "emulators", "datastore", "start", "--host-port=0.0.0.0:8081"]


networks:
  net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
