modules:
  - type: firebase
    config:
      configFile: config/pantel-prod.json
      databaseName: pantel-2decb
      rootPath: test
  - type: ocs
    config:
      projectId: pantel-2decb
      topicId: data-traffic
      lowBalanceThreshold: 0
  - type: api
    config:
      authenticationCachePolicy: maximumSize=10000, expireAfterAccess=10m
      pseudonymEndpoint: http://pseudonym-server:8080
      jerseyClient:
        timeout: 3s
  - type: firebase-app-notifier
    config:
      configFile: config/pantel-prod.json
      databaseName: pantel-2decb
  - type: admin

server:
  applicationConnectors:
    - type: h2c
      port: 8080
      maxConcurrentStreams: 1024
      initialStreamRecvWindow: 65535

logging:
  level: INFO
  loggers:
    org.ostelco: DEBUG
