modules:
  - type: firebase
    config:
      configFile: src/integration-tests/resources/pantel-tests.json
      databaseName: pantel-tests
  - type: ocs
    config:
      projectId: pantel-tests
      topicId: data-traffic
  - type: api
    namespace: https://ostelco
  - type: admin

logging:
  level: INFO
  loggers:
    org.ostelco: DEBUG
