# This config is used as config.yaml when prime is running using docker-compose for Acceptance Testing

modules:
  - type: jersey
    config:
      authenticationCachePolicy: maximumSize=10000, expireAfterAccess=10m
      jerseyClient:
        timeout: 3s
        connectionRequestTimeout: 1s
  - type: firebase
    config:
      configFile: /secret/prime-service-account.json
      rootPath: test
  - type: Imei-lookup
    config:
      csvFile: /config-data/imeiDb.csv
  - type: kyc
    config:
      myInfoApiUri: http://ext-myinfo-emulator:8080
      myInfoApiClientId: STG2-MYINFO-SELF-TEST
      myInfoApiClientSecret: 44d953c796cccebcec9bdc826852857ab412fbe2
      myInfoApiRealm: http://localhost:3001
      myInfoRedirectUri: http://localhost:3001/callback
      myInfoServerPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqWWA2rH1wuBkd1zp0uOh+dnCRRcQWiI89ildk9UGSd3kgzPx1mYEL40cBOBVpSIkbRp65fJDjBm+MhzlHBgWZ1q27S30nczwnzAUJqUfJvLeCW7HLwqwPVSQlqby/n4MV2AKUu0jMacOeXE3Bevm92BEOH9wQhv81Rd7HZXRJGgMecqmVehMT7Mk88xHJvvWD1bYSQL5ADnNz1v0wq/afOVYPWAOl7xYoIgokYJQD3WwnKHVcotZcP8B5mu0AuMnP71JnzjVsRpwuO8N/m28fmzXCY7ARwRpz20Q6oOq09+ZMiJkpdT5TTqEF1u3FxTq5TY8CY60q9L5RqEUNJA9fQIDAQAB
      myInfoClientPrivateKey: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDGBRdsiDqKPGyHgOpzxmSU2EQkm+zYZLvlPlwkwyfFWLndFLZ3saxJS+LIixsFhunrrUT9ZZ0x+bB6MV55o70z4ABOJRFNWx1wbMGqdiC0Fyfpwad3iYpRVjZO+5etHA9JEoaTPoFxv+ktd8kVAL9P5I7/Pi6g1R+B2t2lsaE2bMSwtZqgs55gb7fsCR3Z4nQi7BddYR7MZ2lAMWf7h7Dkm6uRlGhl2RvtmYa6dXFnK3RhIpdQOUT3quyhweMGspowC/tYSG+BNhy1WukbwhIP5vTAvv1WbHTg+WaUUV+pP0TjPQcY73clHxNpI5zrNqDmwD2rogNfePKRUI63yBUfAgMBAAECggEAGy/7xVT25J/jLr+OcRLeIGmJAZW+8P7zpUfoksuQnFHQQwBjBRAJ3Y5jtrESprGdUFRb0oavDHuBtWUt2XmXspWgtRn1xC8sXZExDdxmJRPA0SFbgtgJe51gm3uDmarullPK0lCUqS92Ll3x58ZQfgGdeIHrGP3p84Q/Rk6bGcObcPhDYWSOYKm4i2DPM01bnZG2z4BcrWSseOmeWUxqZcMlGz9GAyepUU/EoqRIHxw/2Y+TGus1JSy5DdhPE0HAEWKZH729ZdoyikOZCMxApQglUkRwkwhtXzVAemm6OSoy3BEWvSEJh/F82tFrmquUoe/xd5JastlBHyD78RAakQKBgQDkHAzo1fowRI19tk7VCPn0zMdF/UTRghtLywc/4xnw1Nd13m+orArOdVzPlQokLVNL81dIVKXnId0Hw/kX8CRyRYz8tkL81spc39DfalZW7QI7Fschfq1Htgkxd/QEjBlIaqjkOjGSbX9xYjYU1Db8PuGoGXWOsYiv9PCsKR056wKBgQDeOzfZSpV5kX8SECJXRA+emyCnO9S29p0W+5BCTQp3OPnmbL7b/mGqBVJ0DC+IiN67Lu8xxzejswqLZqaRvmQuioqH+8mOGpXYZwhShAif2AuixxvL7OK6dvDmMqoKhBI9nZ9+XI60Cd/LjnWgyFO04uq4otnTukmYsSP+fp6wnQKBgEopYH0WjFfDAelcKzcRywouxZ7Yn9Ypoaw7nujDcfydhktY/R5uiLjk6T7H6tsmLU2lGLx4YNPLa6wJp+ODfKX2PMcwjojbYEFftu3cCaQLPE1vs2ANalLFOSnvINOVpOapXq2Mye8cUHHRh1mwQQwzeXQIivLQf2sNjG28lDbvAoGACsh80UJZNmjk7Y9y2yEmUN/eGb9Bdw9IWBEk0tLCKz7MgW3NZQdW3dUcRx1AQTPC+vowCQ5NmNfbLyBv/KpsWgXG6wpAoXCQzMtTEA3wDTGCfweCRcbcyYdz8PeMYK4/5FV9o7gCBKJmBY6IDqEpzqEkGolsYGWtpIcT5Alo0dECgYEA3hzC9NLwumi/1JWm+ASSADTO3rrGo9hicG/WKGzSHD5l1f+IO1SfmUN/6i2JjcnE07eYArNrCfbMgkFavj502ne2fSaYM4p0o147O9Ty8jCyY9vuh/ZGid6qUe3TBI6/okWfmYw6FVbRpNfVEeG7kPfkDW/JdH7qkWTFbh3eH1k=
  - type: neo4j
    config:
      host: neo4j
      protocol: bolt
  - type: analytics
    config:
      projectId: ${GCP_PROJECT_ID}
      dataTrafficTopicId: data-traffic
      purchaseInfoTopicId: purchase-info
      activeUsersTopicId: active-users
  - type: ocs
    config:
      lowBalanceThreshold: 0
      pubSubChannel:
        projectId: ${GCP_PROJECT_ID}
        activateTopicId: ocs-activate
        ccrSubscriptionId: ocs-ccr-sub
  - type: api
  - type: stripe-payment-processor
    config:
      projectId: ${GCP_PROJECT_ID}
      stripeEventTopicId: stripe-event
      stripeEventStoreSubscriptionId: stripe-event-store-sub
      stripeEventReportSubscriptionId: stripe-event-report-sub
      stripeEventRecurringPaymentSubscriptionId: stripe-event-recurring-payment-sub
  - type: firebase-app-notifier
    config:
      configFile: /secret/prime-service-account.json
  - type: admin
  - type: graphql
  - type: scaninfo-store
    config:
      storeType: emulator
      keysetFilePathPrefix: /config/test_keyset_pub_cltxt
server:
  applicationConnectors:
    - type: h2c
      port: 8080
      maxConcurrentStreams: 1024
      initialStreamRecvWindow: 65535

logging:
  level: INFO
  loggers:
    org.ostelco: DEBUG
    # suppress exception logged while connecting to real bigQuery 3 times before connecting to emulator
    com.google.auth.oauth2.ComputeEngineCredentials: ERROR
