# This config is used as config.yaml when prime is running using docker-compose for Acceptance Testing

services:
  - type: firebase
    config:
      configFile: /secret/pantel-prod.json
      databaseName: pantel-2decb
  - type: api
  - type: admin

eventProcessor:
  configFile: /secret/pantel-prod.json
  projectId: pantel-2decb
  topicId: data-traffic

logging:
  level: INFO
  loggers:
    org.ostelco: DEBUG
