# This config is used as config.yaml when prime is running using docker-compose for Acceptance Testing

modules:
  - type: firebase
    config:
      configFile: /secret/pantel-prod.json
      databaseName: pantel-2decb
  - type: ocs
    config:
      projectId: pantel-2decb
      topicId: data-traffic
  - type: api
    namespace: https://ostelco
  - type: admin

logging:
  level: INFO
  loggers:
    org.ostelco: DEBUG
