version: '3.3'
services:
  #    application:
  #      image: ...
  #      environment:
  #      - PUBSUB_EMULATOR_HOST="emulator:8085"
  #      # ...other configurations...
  #     depends_on:
  #      - emulator
  #      - push-gateway


  metrics-extrator:
    container_name: metrics-extrator
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
    - pushgateway
    environment:
    - GOOGLE_APPLICATION_CREDENTIALS=/secret/prime-service-account.json

  emulator:
    container_name: emulator
    image: adilsoncarvalho/gcloud-pubsub-emulator
    ports:
    - "8085:8085"

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    volumes:
    - './prometheus.yml:/etc/prometheus/prometheus.yml'
    - 'prometheus_data:/prometheus'
    ports:
    - '9090:9090'

  # Pushgateway exposes external port 8080, since that is the port
  # that is exposed by the pushgateway in the kubernetes clusters
  pushgateway:
    container_name: pushgateway
    image: prom/pushgateway
    ports:
    - '8080:9091'

  grafana:
    container_name: grafana
    image: grafana/grafana
    environment:
    # Please note that setting the password only works the _FIRST_TIME_
    # the image is built.  After that, it's cached and won't change
    # if you change it in this docker-compose.yml file.  You have
    # been warned!
    - GF_SECURITY_ADMIN_PASSWORD=pass
    depends_on:
    - prometheus
    ports:
    - '3000:3000'
    volumes:
    - 'grafana_data:/var/lib/grafana'

volumes:
  prometheus_data: {}
  grafana_data: {}
